/*
 * Logger.h
 *
 *  Created on: 29.05.2013
 *      Author: Johannes Morgenroth <morgenroth@ibr.cs.tu-bs.de>
 */

#ifndef WIFIP2P_LOGGER_H_
#define WIFIP2P_LOGGER_H_

namespace wifip2p {

class Logger {

public:
	virtual ~Logger() { };

	/**
	 * Provides log messages generated by the library.
	 *
	 * @tag A tag indicating which part is generating the message.
	 * @msg The message itself.
	 */
	virtual void log(std::string tag, std::string msg) { };

	/**
	 * Provides error messages generated by the library.
	 *
	 * @tag A tag indicating which part is generating the message.
	 * @msg The message itself.
	 */
	virtual void log_err(std::string tag, std::string msg) { };

	/**
	 * Provides debug messages generated by the library.
	 *
	 * @debug A verbosity number of this debug message
	 * @tag A tag indicating which part is generating the message.
	 * @msg The message itself.
	 */
	virtual void log_debug(int debug, std::string tag, std::string msg) { };
};

}

#endif /* WIFIP2P_LOGGER_H_ */
